name: hymate_challenge
description: "Hymate Technical Challenge"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  logger: ^2.3.0
  quiver: ^3.2.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
